-- ============================================================
-- E2B R3 ICSR Database Schema  (SQLite / PostgreSQL compatible)
-- Generated by E2B R3 Import/Export Module v1.0.0
-- Standard: ICH E2B(R3)  |  License: GPL v3
-- ============================================================

CREATE TABLE IF NOT EXISTS icsr (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    imported_at TEXT    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS c1_identification (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                         INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    sender_safety_report_unique_id  TEXT,
    date_creation                   TEXT,
    type_report                     TEXT,
    date_first_received             TEXT,
    date_most_recent                TEXT,
    additional_documents_available  TEXT,
    fulfil_local_criteria           TEXT,
    worldwide_unique_case_id        TEXT,
    first_sender                    TEXT,
    other_case_ids_previous         TEXT,
    report_nullification_amendment  TEXT,
    reason_nullification_amendment  TEXT
);

CREATE TABLE IF NOT EXISTS c1_documents (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    c1_id           INTEGER REFERENCES c1_identification(id) ON DELETE CASCADE,
    document_name   TEXT
);

CREATE TABLE IF NOT EXISTS c1_source_case_ids (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    c1_id       INTEGER REFERENCES c1_identification(id) ON DELETE CASCADE,
    source      TEXT,
    case_id     TEXT
);

CREATE TABLE IF NOT EXISTS c1_linked_reports (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    c1_id           INTEGER REFERENCES c1_identification(id) ON DELETE CASCADE,
    report_number   TEXT
);

CREATE TABLE IF NOT EXISTS c2_primary_sources (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                     INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    reporter_title              TEXT,
    reporter_given_name         TEXT,
    reporter_middle_name        TEXT,
    reporter_family_name        TEXT,
    reporter_organisation       TEXT,
    reporter_department         TEXT,
    reporter_street             TEXT,
    reporter_city               TEXT,
    reporter_state              TEXT,
    reporter_postcode           TEXT,
    reporter_telephone          TEXT,
    reporter_country_code       TEXT,
    qualification               TEXT,
    primary_source_regulatory   TEXT
);

CREATE TABLE IF NOT EXISTS c3_sender (
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                 INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    sender_type             TEXT,
    sender_organisation     TEXT,
    sender_department       TEXT,
    sender_title            TEXT,
    sender_given_name       TEXT,
    sender_middle_name      TEXT,
    sender_family_name      TEXT,
    sender_street           TEXT,
    sender_city             TEXT,
    sender_state            TEXT,
    sender_postcode         TEXT,
    sender_country_code     TEXT,
    sender_telephone        TEXT,
    sender_fax              TEXT,
    sender_email            TEXT
);

CREATE TABLE IF NOT EXISTS c4_literature (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    literature_reference TEXT
);

CREATE TABLE IF NOT EXISTS c5_study (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    study_name          TEXT,
    sponsor_study_number TEXT,
    study_type          TEXT
);

CREATE TABLE IF NOT EXISTS c5_study_registrations (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    c5_id                       INTEGER REFERENCES c5_study(id) ON DELETE CASCADE,
    registration_number         TEXT,
    registration_country        TEXT
);

CREATE TABLE IF NOT EXISTS d_patient (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                         INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    patient_initials                TEXT,
    medical_record_gp               TEXT,
    medical_record_specialist       TEXT,
    medical_record_hospital         TEXT,
    medical_record_investigation    TEXT,
    date_birth                      TEXT,
    age_onset_num                   TEXT,
    age_onset_unit                  TEXT,
    gestation_period_num            TEXT,
    gestation_period_unit           TEXT,
    age_group                       TEXT,
    body_weight_kg                  TEXT,
    height_cm                       TEXT,
    sex                             TEXT,
    last_menstrual_period           TEXT,
    text_medical_history            TEXT,
    concomitant_therapies           TEXT,
    date_death                      TEXT,
    autopsy_done                    TEXT,
    parent_identification           TEXT,
    parent_date_birth               TEXT,
    parent_age_num                  TEXT,
    parent_age_unit                 TEXT,
    parent_last_menstrual_period    TEXT,
    parent_body_weight_kg           TEXT,
    parent_height_cm                TEXT,
    parent_sex                      TEXT,
    parent_text_medical_history     TEXT
);

CREATE TABLE IF NOT EXISTS d_medical_history (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id                  INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    meddra_version              TEXT,
    meddra_code                 TEXT,
    start_date                  TEXT,
    continuing                  TEXT,
    end_date                    TEXT,
    comments                    TEXT,
    family_history              TEXT
);

CREATE TABLE IF NOT EXISTS d_past_drugs (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id                  INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    drug_name                   TEXT,
    mpid_version                TEXT,
    mpid                        TEXT,
    phpid_version               TEXT,
    phpid                       TEXT,
    start_date                  TEXT,
    end_date                    TEXT,
    indication_meddra_version   TEXT,
    indication_meddra_code      TEXT,
    reaction_meddra_version     TEXT,
    reaction_meddra_code        TEXT
);

CREATE TABLE IF NOT EXISTS d_cause_death (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id      INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    meddra_version  TEXT,
    meddra_code     TEXT,
    cause_text      TEXT
);

CREATE TABLE IF NOT EXISTS d_autopsy_cause (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id      INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    meddra_version  TEXT,
    meddra_code     TEXT,
    cause_text      TEXT
);

CREATE TABLE IF NOT EXISTS e_reactions (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                         INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    reaction_native_language        TEXT,
    reaction_language               TEXT,
    reaction_translation            TEXT,
    meddra_version                  TEXT,
    meddra_code                     TEXT,
    term_highlighted                TEXT,
    seriousness_death               TEXT,
    seriousness_life_threatening    TEXT,
    seriousness_hospitalisation     TEXT,
    seriousness_disabling           TEXT,
    seriousness_congenital          TEXT,
    seriousness_other               TEXT,
    date_start                      TEXT,
    date_end                        TEXT,
    duration_num                    TEXT,
    duration_unit                   TEXT,
    outcome                         TEXT,
    medical_confirmation            TEXT,
    country                         TEXT
);

CREATE TABLE IF NOT EXISTS f_tests (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    test_date           TEXT,
    test_name           TEXT,
    meddra_version      TEXT,
    meddra_code         TEXT,
    result_code         TEXT,
    result_value        TEXT,
    result_unit         TEXT,
    result_unstructured TEXT,
    normal_low          TEXT,
    normal_high         TEXT,
    comments            TEXT,
    more_info_available TEXT
);

CREATE TABLE IF NOT EXISTS g_drugs (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                     INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    drug_role                   TEXT,
    mpid_version                TEXT,
    mpid                        TEXT,
    phpid_version               TEXT,
    phpid                       TEXT,
    product_name                TEXT,
    country_obtained            TEXT,
    investigational_blinded     TEXT,
    authorisation_number        TEXT,
    authorisation_country       TEXT,
    holder_name                 TEXT,
    cumulative_dose_num         TEXT,
    cumulative_dose_unit        TEXT,
    gestation_period_num        TEXT,
    gestation_period_unit       TEXT,
    action_taken                TEXT,
    additional_info_text        TEXT
);

CREATE TABLE IF NOT EXISTS g_substances (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id         INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    substance_name  TEXT,
    termid_version  TEXT,
    termid          TEXT,
    strength_num    TEXT,
    strength_unit   TEXT
);

CREATE TABLE IF NOT EXISTS g_dosages (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id                     INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    dose_num                    TEXT,
    dose_unit                   TEXT,
    number_units_interval       TEXT,
    interval_unit               TEXT,
    date_start                  TEXT,
    date_last_admin             TEXT,
    duration_num                TEXT,
    duration_unit               TEXT,
    batch_lot_number            TEXT,
    dosage_text                 TEXT,
    dose_form                   TEXT,
    route_administration        TEXT,
    parent_route_administration TEXT
);

CREATE TABLE IF NOT EXISTS g_indications (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id             INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    indication_text     TEXT,
    meddra_version      TEXT,
    meddra_code         TEXT
);

CREATE TABLE IF NOT EXISTS g_reaction_matrix (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id                     INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    reaction_index              TEXT,
    interval_admin_reaction_num TEXT,
    interval_admin_reaction_unit TEXT,
    interval_last_dose_num      TEXT,
    interval_last_dose_unit     TEXT,
    recur_readministration      TEXT
);

CREATE TABLE IF NOT EXISTS g_assessments (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    matrix_id       INTEGER REFERENCES g_reaction_matrix(id) ON DELETE CASCADE,
    source          TEXT,
    method          TEXT,
    result          TEXT
);

CREATE TABLE IF NOT EXISTS g_additional_info (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id     INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    info_code   TEXT
);

CREATE TABLE IF NOT EXISTS h_narrative (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    case_narrative      TEXT,
    reporter_comments   TEXT,
    sender_comments     TEXT
);

CREATE TABLE IF NOT EXISTS h_sender_diagnosis (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    narrative_id    INTEGER REFERENCES h_narrative(id) ON DELETE CASCADE,
    meddra_version  TEXT,
    meddra_code     TEXT
);

CREATE TABLE IF NOT EXISTS h_reporter_comments_native (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    narrative_id    INTEGER REFERENCES h_narrative(id) ON DELETE CASCADE,
    comments_text   TEXT,
    language        TEXT
);


-- Data exported from ICSR

INSERT INTO icsr () VALUES ();
-- (icsr row uses auto-generated id=1 below)

INSERT INTO c1_identification (icsr_id, sender_safety_report_unique_id, date_creation, type_report, date_first_received, date_most_recent, additional_documents_available, fulfil_local_criteria, worldwide_unique_case_id, first_sender, other_case_ids_previous, report_nullification_amendment, reason_nullification_amendment) VALUES (1, 'JP-DSJP-DSJ-2009-98765-1', '20120720100001+09', '1', '20090622', '20100412', 'true', 'true', 'JP-DSJP-DSJ-2009-98765-1', '2', '[No Information]', NULL, NULL);
INSERT INTO c2_primary_sources (icsr_id, reporter_title, reporter_given_name, reporter_middle_name, reporter_family_name, reporter_organisation, reporter_department, reporter_street, reporter_city, reporter_state, reporter_postcode, reporter_telephone, reporter_country_code, qualification, primary_source_regulatory) VALUES (1, NULL, 'Kyoko', NULL, 'Kudo', 'Kyushu University', 'Respiratory', '3-1-1 Maidashi, Higashi-ku', 'Fukuoka', 'Fukuoka', '812-8582', NULL, 'JP', '1', '1');
INSERT INTO c3_sender (icsr_id, sender_type, sender_organisation, sender_department, sender_title, sender_given_name, sender_middle_name, sender_family_name, sender_street, sender_city, sender_state, sender_postcode, sender_country_code, sender_telephone, sender_fax, sender_email) VALUES (1, '1', 'Daiichi Sankyo Company, Limited', 'Pharmacovigilance', NULL, 'Hanako', NULL, 'Yamada', '3-5-1 Nihonbashi Honcho', 'Chuo-ku', 'Tokyo', '103-8426', 'JP', '8199999999', '8188888888', 'xxxx@xxxx.co.jp');
INSERT INTO c4_literature (icsr_id, literature_reference) VALUES (1, 'K. Kudo, et al. (2009) A Case of Heparin-Induced Thrombocytopenia and
Disseminated Intravascular Coagulation during Treatment for Drug-Induced
Pneumonia. Journal of Japanese Respiratory Society, The 49th Annual Meeting of
The Japanese Respiratory Society, 47: p.316');
INSERT INTO d_patient (icsr_id, patient_initials, medical_record_gp, medical_record_specialist, medical_record_hospital, medical_record_investigation, date_birth, age_onset_num, age_onset_unit, gestation_period_num, gestation_period_unit, age_group, body_weight_kg, height_cm, sex, last_menstrual_period, text_medical_history, concomitant_therapies, date_death, autopsy_done, parent_identification, parent_date_birth, parent_age_num, parent_age_unit, parent_last_menstrual_period, parent_body_weight_kg, parent_height_cm, parent_sex, parent_text_medical_history) VALUES (1, 'T.O.', NULL, NULL, NULL, NULL, '19260412', '81', 'a', NULL, NULL, NULL, '59', '153', '2', '[Not Asked]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO d_medical_history (patient_id, meddra_version, meddra_code, start_date, continuing, end_date, comments, family_history) VALUES (1, '15', '10020603', '200807', 'true', NULL, NULL, NULL);
INSERT INTO e_reactions (icsr_id, reaction_native_language, reaction_language, reaction_translation, meddra_version, meddra_code, term_highlighted, seriousness_death, seriousness_life_threatening, seriousness_hospitalisation, seriousness_disabling, seriousness_congenital, seriousness_other, date_start, date_end, duration_num, duration_unit, outcome, medical_confirmation, country) VALUES (1, '間質性肺炎', 'JA', 'INTERSTITIAL PNEUMONIA', '15', '10022617', '3', '[No Information]', 'true', 'true', '[No Information]', '[No Information]', '[No Information]', '20081009', '20081201', '54', 'd', '1', NULL, 'JP');
INSERT INTO f_tests (icsr_id, test_date, test_name, meddra_version, meddra_code, result_code, result_value, result_unit, result_unstructured, normal_low, normal_high, comments, more_info_available) VALUES (1, '20081010', NULL, '15', '10006824', NULL, '4.46', 'mg/dL', NULL, NULL, '0.1', NULL, 'false');
INSERT INTO f_tests (icsr_id, test_date, test_name, meddra_version, meddra_code, result_code, result_value, result_unit, result_unstructured, normal_low, normal_high, comments, more_info_available) VALUES (1, '20081010', 'DLST', '', '', NULL, NULL, NULL, 'MEVALOTIN(-), ALTAT(-), AMLODIN(-), BLOPRESS(-), LASIX (-)', NULL, NULL, NULL, NULL);
INSERT INTO g_drugs (icsr_id, drug_role, mpid_version, mpid, phpid_version, phpid, product_name, country_obtained, investigational_blinded, authorisation_number, authorisation_country, holder_name, cumulative_dose_num, cumulative_dose_unit, gestation_period_num, gestation_period_unit, action_taken, additional_info_text) VALUES (1, '1', '1.01', '218901001', NULL, NULL, 'MEVALOTIN', NULL, NULL, '20300AMZ00671000', 'JP', 'Daiichi Sankyo Company, Limited', NULL, NULL, NULL, NULL, '1', NULL);
INSERT INTO g_substances (drug_id, substance_name, termid_version, termid, strength_num, strength_unit) VALUES (1, 'PRAVASTATIN SODIUM', '1.52', '568874', '20', 'mg');
INSERT INTO g_dosages (drug_id, dose_num, dose_unit, number_units_interval, interval_unit, date_start, date_last_admin, duration_num, duration_unit, batch_lot_number, dosage_text, dose_form, route_administration, parent_route_administration) VALUES (1, '20', 'mg', NULL, NULL, '200807', '20081006', NULL, NULL, NULL, NULL, 'TABLET', 'PER ORAL', NULL);
INSERT INTO g_indications (drug_id, indication_text, meddra_version, meddra_code) VALUES (1, 'HYPERLIPIDAEMIA', '15', '10062060');
INSERT INTO h_narrative (icsr_id, case_narrative, reporter_comments, sender_comments) VALUES (1, 'An 81-year-old female patient received Mevalotin (pravastatin sodium) 20mg  for hyperlipidemia since July 2008. The patient experienced interstitial pneumonia on 08 October 2008 (inpatient hospitalization).', 'Although the results of DLSTs were all negative, drug-induced pneumonia was most considered from the onset of interstitial pneumonia, the condition of the shadows and the clinical course.', 'This is a spontaneously received case reported by a literature that is categorized as serious due to inpatient hospitalization. Daiichi Sankyo''s assessment of the causal relationship between interstitial pneumonia and Mevalotin is related.');
INSERT INTO h_reporter_comments_native (narrative_id, comments_text, language) VALUES (1, 'DLSTの結果は陰性であるが間質性肺炎の発症時期、陰影の性状、経過からも薬剤性肺炎が最も考えられる。原因薬剤は特定できていない。', 'JA');