from typing import Dict, Set

__version__ = '1.0.0'
__author__  = 'E2B4Free Project'
__license__ = 'GPL-3.0'

FIELD_LABELS: Dict[str, str] = {
    'c_1_identification_case_safety_report': 'C.1 Identification of the Case Safety Report',
    'c_1_1_sender_safety_report_unique_id': 'C.1.1 Sender Safety Report Unique ID',
    'c_1_2_date_creation': 'C.1.2 Date of Creation',
    'c_1_3_type_report': 'C.1.3 Type of Report',
    'c_1_4_date_report_first_received_source': 'C.1.4 Date Report First Received from Source',
    'c_1_5_date_most_recent_information': 'C.1.5 Date of Most Recent Information',
    'c_1_6_1_additional_documents_available': 'C.1.6.1 Additional Documents Available',
    'c_1_6_1_r_documents_held_sender': 'C.1.6.1(R) Documents Held by Sender',
    'c_1_6_1_r_1_documents_held_sender': 'C.1.6.1(R).1 Documents Held by Sender',
    'c_1_7_fulfil_local_criteria_expedited_report': 'C.1.7 Fulfil Local Criteria for Expedited Report',
    'c_1_8_1_worldwide_unique_case_identification_number': 'C.1.8.1 Worldwide Unique Case Identification Number',
    'c_1_8_2_first_sender': 'C.1.8.2 First Sender',
    'c_1_9_1_other_case_ids_previous_transmissions': 'C.1.9.1 Other Case IDs — Previous Transmissions',
    'c_1_9_1_r_source_case_id': 'C.1.9.1(R) Source Case ID',
    'c_1_9_1_r_1_source_case_id': 'C.1.9.1(R).1 Source Case ID',
    'c_1_9_1_r_2_case_id': 'C.1.9.1(R).2 Case ID',
    'c_1_10_r_identification_number_report_linked': 'C.1.10(R) Identification Number of Report Linked',
    'c_1_11_1_report_nullification_amendment': 'C.1.11.1 Report Nullification / Amendment',
    'c_1_11_2_reason_nullification_amendment': 'C.1.11.2 Reason for Nullification / Amendment',
    'c_2_r_primary_source_information': 'C.2(R) Primary Source Information',
    'c_2_r_1_1_reporter_title': 'C.2.r.1.1 Reporter Title',
    'c_2_r_1_2_reporter_given_name': 'C.2.r.1.2 Reporter Given Name',
    'c_2_r_1_3_reporter_middle_name': 'C.2.r.1.3 Reporter Middle Name',
    'c_2_r_1_4_reporter_family_name': 'C.2.r.1.4 Reporter Family Name',
    'c_2_r_2_1_reporter_organisation': 'C.2.r.2.1 Reporter Organisation',
    'c_2_r_2_2_reporter_department': 'C.2.r.2.2 Reporter Department',
    'c_2_r_2_3_reporter_street': 'C.2.r.2.3 Reporter Street',
    'c_2_r_2_4_reporter_city': 'C.2.r.2.4 Reporter City',
    'c_2_r_2_5_reporter_state_province': 'C.2.r.2.5 Reporter State/Province',
    'c_2_r_2_6_reporter_postcode': 'C.2.r.2.6 Reporter Postcode',
    'c_2_r_2_7_reporter_telephone': 'C.2.r.2.7 Reporter Telephone',
    'c_2_r_3_reporter_country_code': 'C.2.r.3 Reporter Country Code',
    'c_2_r_4_qualification': 'C.2.r.4 Qualification',
    'c_2_r_5_primary_source_regulatory_purposes': 'C.2.r.5 Primary Source for Regulatory Purposes',
    'c_3_information_sender_case_safety_report': 'C.3 Information Sender of Case Safety Report',
    'c_3_1_sender_type': 'C.3.1 Sender Type',
    'c_3_2_sender_organisation': 'C.3.2 Sender Organisation',
    'c_3_3_1_sender_department': 'C.3.3.1 Sender Department',
    'c_3_3_2_sender_title': 'C.3.3.2 Sender Title',
    'c_3_3_3_sender_given_name': 'C.3.3.3 Sender Given Name',
    'c_3_3_4_sender_middle_name': 'C.3.3.4 Sender Middle Name',
    'c_3_3_5_sender_family_name': 'C.3.3.5 Sender Family Name',
    'c_3_4_1_sender_street_address': 'C.3.4.1 Sender Street Address',
    'c_3_4_2_sender_city': 'C.3.4.2 Sender City',
    'c_3_4_3_sender_state_province': 'C.3.4.3 Sender State/Province',
    'c_3_4_4_sender_postcode': 'C.3.4.4 Sender Postcode',
    'c_3_4_5_sender_country_code': 'C.3.4.5 Sender Country Code',
    'c_3_4_6_sender_telephone': 'C.3.4.6 Sender Telephone',
    'c_3_4_7_sender_fax': 'C.3.4.7 Sender Fax',
    'c_3_4_8_sender_email': 'C.3.4.8 Sender Email',
    'c_4_r_literature_reference': 'C.4(R) Literature Reference',
    'c_4_r_1_literature_reference': 'C.4.r.1 Literature Reference',
    'c_5_study_identification': 'C.5 Study Identification',
    'c_5_1_r_study_registration': 'C.5.1(R) Study Registration',
    'c_5_1_r_1_study_registration_number': 'C.5.1.r.1 Study Registration Number',
    'c_5_1_r_2_study_registration_country': 'C.5.1.r.2 Study Registration Country',
    'c_5_2_study_name': 'C.5.2 Study Name',
    'c_5_3_sponsor_study_number': 'C.5.3 Sponsor Study Number',
    'c_5_4_study_type_reaction': 'C.5.4 Study Type Where Reaction(s)/Event(s) Were Observed',
    'd_patient_characteristics': 'D Patient Characteristics',
    'd_1_patient': 'D.1 Patient (name or initials)',
    'd_1_1_1_medical_record_number_source_gp': 'D.1.1.1 Medical Record Number (GP)',
    'd_1_1_2_medical_record_number_source_specialist': 'D.1.1.2 Medical Record Number (Specialist)',
    'd_1_1_3_medical_record_number_source_hospital': 'D.1.1.3 Medical Record Number (Hospital)',
    'd_1_1_4_medical_record_number_source_investigation': 'D.1.1.4 Medical Record Number (Investigation)',
    'd_2_1_date_birth': 'D.2.1 Date of Birth',
    'd_2_2a_age_onset_reaction_num': 'D.2.2a Age at Time of Onset (Number)',
    'd_2_2b_age_onset_reaction_unit': 'D.2.2b Age Unit',
    'd_2_2_1a_gestation_period_reaction_foetus_num': 'D.2.2.1a Gestation Period (Number)',
    'd_2_2_1b_gestation_period_reaction_foetus_unit': 'D.2.2.1b Gestation Period Unit',
    'd_2_3_patient_age_group': 'D.2.3 Patient Age Group',
    'd_3_body_weight': 'D.3 Body Weight (kg)',
    'd_4_height': 'D.4 Height (cm)',
    'd_5_sex': 'D.5 Sex',
    'd_6_last_menstrual_period_date': 'D.6 Last Menstrual Period Date',
    'd_7_1_r_structured_information_medical_history': 'D.7.1(R) Structured Medical History',
    'd_7_2_text_medical_history': 'D.7.2 Text for Relevant Medical History',
    'd_7_3_concomitant_therapies': 'D.7.3 Concomitant Therapies',
    'd_8_r_past_drug_history': 'D.8(R) Relevant Past Drug History',
    'd_9_1_date_death': 'D.9.1 Date of Death',
    'd_9_2_r_cause_death': 'D.9.2(R) Cause of Death',
    'd_9_3_autopsy': 'D.9.3 Was Autopsy Done?',
    'd_9_4_r_autopsy_determined_cause_death': 'D.9.4(R) Autopsy Determined Cause(s) of Death',
    'd_10_1_parent_identification': 'D.10.1 Parent Identification',
    'd_10_2_1_date_birth_parent': 'D.10.2.1 Date of Birth of Parent',
    'd_10_2_2a_age_parent_num': 'D.10.2.2a Age of Parent (Number)',
    'd_10_2_2b_age_parent_unit': 'D.10.2.2b Age of Parent Unit',
    'd_10_3_last_menstrual_period_date_parent': 'D.10.3 Last Menstrual Period Date of Parent',
    'd_10_4_body_weight_parent': 'D.10.4 Body Weight of Parent (kg)',
    'd_10_5_height_parent': 'D.10.5 Height of Parent (cm)',
    'd_10_6_sex_parent': 'D.10.6 Sex of Parent',
    'd_10_7_1_r_structured_information_parent_meddra_code': 'D.10.7.1(R) Parent Medical History',
    'd_10_7_2_text_medical_history_parent': 'D.10.7.2 Text for Parent Medical History',
    'd_10_8_r_past_drug_history_parent': 'D.10.8(R) Past Drug History of Parent',
    'e_i_reaction_event': 'E.i Reaction(s) / Event(s)',
    'e_i_1_1a_reaction_primary_source_native_language': 'E.i.1.1a Reaction/Event as Reported (native language)',
    'e_i_1_1b_reaction_primary_source_language': 'E.i.1.1b Language',
    'e_i_1_2_reaction_primary_source_translation': 'E.i.1.2 Reaction/Event as Reported (English translation)',
    'e_i_2_1a_meddra_version_reaction': 'E.i.2.1a MedDRA Version (Reaction)',
    'e_i_2_1b_reaction_meddra_code': 'E.i.2.1b Reaction/Event MedDRA Code',
    'e_i_3_1_term_highlighted_reporter': 'E.i.3.1 Term Highlighted by Reporter',
    'e_i_3_2a_results_death': 'E.i.3.2a Results in Death',
    'e_i_3_2b_life_threatening': 'E.i.3.2b Life Threatening',
    'e_i_3_2c_caused_prolonged_hospitalisation': 'E.i.3.2c Caused/Prolonged Hospitalisation',
    'e_i_3_2d_disabling_incapacitating': 'E.i.3.2d Disabling/Incapacitating',
    'e_i_3_2e_congenital_anomaly_birth_defect': 'E.i.3.2e Congenital Anomaly / Birth Defect',
    'e_i_3_2f_other_medically_important_condition': 'E.i.3.2f Other Medically Important Condition',
    'e_i_4_date_start_reaction': 'E.i.4 Date of Start of Reaction/Event',
    'e_i_5_date_end_reaction': 'E.i.5 Date of End of Reaction/Event',
    'e_i_6a_duration_reaction_num': 'E.i.6a Duration of Reaction/Event (Number)',
    'e_i_6b_duration_reaction_unit': 'E.i.6b Duration Unit',
    'e_i_7_outcome_reaction_last_observation': 'E.i.7 Outcome of Reaction/Event at Last Observation',
    'e_i_8_medical_confirmation_healthcare_professional': 'E.i.8 Medical Confirmation by Healthcare Professional',
    'e_i_9_identification_country_reaction': 'E.i.9 Country Where Reaction Occurred',
    'f_r_results_tests_procedures_investigation_patient': 'F.r Results of Tests and Procedures',
    'f_r_1_test_date': 'F.r.1 Test Date',
    'f_r_2_1_test_name': 'F.r.2.1 Test Name',
    'f_r_2_2a_meddra_version_test_name': 'F.r.2.2a MedDRA Version (Test Name)',
    'f_r_2_2b_test_name_meddra_code': 'F.r.2.2b Test Name MedDRA Code',
    'f_r_3_1_test_result_code': 'F.r.3.1 Test Result (code)',
    'f_r_3_2_test_result_val_qual': 'F.r.3.2 Test Result (value/qualifier)',
    'f_r_3_3_test_result_unit': 'F.r.3.3 Test Result Unit',
    'f_r_3_4_result_unstructured_data': 'F.r.3.4 Result Unstructured Data',
    'f_r_4_normal_low_value': 'F.r.4 Normal Low Value',
    'f_r_5_normal_high_value': 'F.r.5 Normal High Value',
    'f_r_6_comments': 'F.r.6 Comments',
    'f_r_7_more_information_available': 'F.r.7 More Information Available',
    'g_k_drug_information': 'G.k Drug(s) Information',
    'g_k_1_characterisation_drug_role': 'G.k.1 Characterisation of Drug Role',
    'g_k_2_1_1a_mpid_version': 'G.k.2.1.1a MPID Version',
    'g_k_2_1_1b_mpid': 'G.k.2.1.1b Medicinal Product ID (MPID)',
    'g_k_2_1_2a_phpid_version': 'G.k.2.1.2a PhPID Version',
    'g_k_2_1_2b_phpid': 'G.k.2.1.2b Pharmaceutical Product ID (PhPID)',
    'g_k_2_2_medicinal_product_name_primary_source': 'G.k.2.2 Medicinal Product Name (Primary Source)',
    'g_k_2_3_r_substance_id_strength': 'G.k.2.3(R) Substance / Strength',
    'g_k_2_3_r_1_substance_name': 'G.k.2.3.r.1 Substance Name',
    'g_k_2_3_r_2a_substance_termid_version': 'G.k.2.3.r.2a Substance Term ID Version',
    'g_k_2_3_r_2b_substance_termid': 'G.k.2.3.r.2b Substance Term ID',
    'g_k_2_3_r_3a_strength_num': 'G.k.2.3.r.3a Strength (Number)',
    'g_k_2_3_r_3b_strength_unit': 'G.k.2.3.r.3b Strength Unit',
    'g_k_2_4_identification_country_drug_obtained': 'G.k.2.4 Country Where Drug Was Obtained',
    'g_k_2_5_investigational_product_blinded': 'G.k.2.5 Investigational Product Blinded',
    'g_k_3_1_authorisation_application_number': 'G.k.3.1 Authorisation / Application Number',
    'g_k_3_2_country_authorisation_application': 'G.k.3.2 Country of Authorisation / Application',
    'g_k_3_3_name_holder_applicant': 'G.k.3.3 Name of Holder / Applicant',
    'g_k_4_r_dosage_information': 'G.k.4(R) Dosage and Relevant Information',
    'g_k_4_r_1a_dose_num': 'G.k.4.r.1a Dose (Number)',
    'g_k_4_r_1b_dose_unit': 'G.k.4.r.1b Dose Unit',
    'g_k_4_r_2_number_units_interval': 'G.k.4.r.2 Number of Units in the Interval',
    'g_k_4_r_3_definition_interval_unit': 'G.k.4.r.3 Definition of the Interval Unit',
    'g_k_4_r_4_date_time_drug': 'G.k.4.r.4 Date/Time of Start of Drug',
    'g_k_4_r_5_date_time_last_administration': 'G.k.4.r.5 Date/Time of Last Administration',
    'g_k_4_r_6a_duration_drug_administration_num': 'G.k.4.r.6a Duration of Drug Administration (Number)',
    'g_k_4_r_6b_duration_drug_administration_unit': 'G.k.4.r.6b Duration of Drug Administration Unit',
    'g_k_4_r_7_batch_lot_number': 'G.k.4.r.7 Batch/Lot Number',
    'g_k_4_r_8_dosage_text': 'G.k.4.r.8 Dosage Text',
    'g_k_4_r_9_1_pharmaceutical_dose_form': 'G.k.4.r.9.1 Pharmaceutical Dose Form',
    'g_k_4_r_10_1_route_administration': 'G.k.4.r.10.1 Route of Administration',
    'g_k_4_r_11_1_parent_route_administration': 'G.k.4.r.11.1 Parent Route of Administration',
    'g_k_5a_cumulative_dose_first_reaction_num': 'G.k.5a Cumulative Dose to First Reaction (Number)',
    'g_k_5b_cumulative_dose_first_reaction_unit': 'G.k.5b Cumulative Dose Unit',
    'g_k_6a_gestation_period_exposure_num': 'G.k.6a Gestation Period at Time of Exposure (Number)',
    'g_k_6b_gestation_period_exposure_unit': 'G.k.6b Gestation Period Unit',
    'g_k_7_r_indication_use_case': 'G.k.7(R) Indication(s) for Use in Case',
    'g_k_7_r_1_indication_primary_source': 'G.k.7.r.1 Indication (Primary Source)',
    'g_k_7_r_2a_meddra_version_indication': 'G.k.7.r.2a MedDRA Version (Indication)',
    'g_k_7_r_2b_indication_meddra_code': 'G.k.7.r.2b Indication MedDRA Code',
    'g_k_8_action_taken_drug': 'G.k.8 Action(s) Taken with Drug',
    'g_k_9_i_drug_reaction_matrix': 'G.k.9.i Drug-Reaction Matrix',
    'g_k_9_i_1_reaction_assessed': 'G.k.9.i.1 Reaction/Event Assessed',
    'g_k_9_i_2_r_assessment_relatedness_drug_reaction': 'G.k.9.i.2(R) Assessment of Relatedness',
    'g_k_9_i_2_r_1_source_assessment': 'G.k.9.i.2.r.1 Source of Assessment',
    'g_k_9_i_2_r_2_method_assessment': 'G.k.9.i.2.r.2 Method of Assessment',
    'g_k_9_i_2_r_3_result_assessment': 'G.k.9.i.2.r.3 Result of Assessment',
    'g_k_9_i_3_1a_interval_drug_administration_reaction_num': 'G.k.9.i.3.1a Interval Drug→Reaction (Number)',
    'g_k_9_i_3_1b_interval_drug_administration_reaction_unit': 'G.k.9.i.3.1b Interval Unit',
    'g_k_9_i_3_2a_interval_last_dose_drug_reaction_num': 'G.k.9.i.3.2a Interval Last Dose→Reaction (Number)',
    'g_k_9_i_3_2b_interval_last_dose_drug_reaction_unit': 'G.k.9.i.3.2b Interval Unit',
    'g_k_9_i_4_reaction_recur_readministration': 'G.k.9.i.4 Reaction Recur on Readministration?',
    'g_k_10_r_additional_information_drug': 'G.k.10(R) Additional Information on Drug',
    'g_k_11_additional_information_drug': 'G.k.11 Additional Information on Drug (free text)',
    'h_narrative_case_summary': 'H Narrative Case Summary and Comments',
    'h_1_case_narrative': 'H.1 Case Narrative',
    'h_2_reporter_comments': "H.2 Reporter's Comments",
    'h_3_r_sender_diagnosis_meddra_code': "H.3(R) Sender's Diagnosis MedDRA Code",
    'h_3_r_1a_meddra_version_sender_diagnosis': 'H.3.r.1a MedDRA Version (Sender Diagnosis)',
    'h_3_r_1b_sender_diagnosis_meddra_code': "H.3.r.1b Sender's Diagnosis MedDRA Code",
    'h_4_sender_comments': "H.4 Sender's Comments",
    'h_5_r_case_summary_reporter_comments_native_language': 'H.5(R) Case Summary (native language)',
    'h_5_r_1a_case_summary_reporter_comments_text': 'H.5.r.1a Case Summary Text (native language)',
    'h_5_r_1b_case_summary_reporter_comments_language': 'H.5.r.1b Language',
}

ENUM_LABELS: Dict[str, Dict[str, str]] = {
    'c_1_3_type_report': {
        '1': 'Spontaneous Report',
        '2': 'Report from Study',
        '3': 'Other',
        '4': 'Not Available to Sender (from Study)',
    },
    'c_1_8_2_first_sender': {'1': 'Regulator', '2': 'Other'},
    'c_1_11_1_report_nullification_amendment': {'1': 'Nullification', '2': 'Amendment'},
    'c_2_r_4_qualification': {
        '1': 'Physician', '2': 'Pharmacist', '3': 'Other Health Professional',
        '4': 'Lawyer', '5': 'Consumer or Other Non-Health Professional',
    },
    'c_2_r_5_primary_source_regulatory_purposes': {'1': 'Primary'},
    'c_3_1_sender_type': {
        '1': 'Pharmaceutical Company', '2': 'Regulatory Authority', '3': 'Health Professional',
        '4': 'Regional Pharmacovigilance Centre',
        '5': 'WHO Collaborating Centres for International Drug Monitoring',
        '6': 'Other', '7': 'Patient or Consumer',
    },
    'c_5_4_study_type_reaction': {
        '1': 'Clinical Trials', '2': 'Individual Patient Use', '3': 'Other Studies',
    },
    'd_2_3_patient_age_group': {
        '0': 'Foetus', '1': 'Neonate', '2': 'Infant', '3': 'Child',
        '4': 'Adolescent', '5': 'Adult', '6': 'Elderly',
    },
    'd_5_sex': {'1': 'Male', '2': 'Female'},
    'd_10_6_sex_parent': {'1': 'Male', '2': 'Female'},
    'e_i_3_1_term_highlighted_reporter': {
        '1': 'Yes (Not Serious)', '2': 'No (Not Serious)',
        '3': 'Yes (Serious)', '4': 'No (Serious)',
    },
    'e_i_7_outcome_reaction_last_observation': {
        '0': 'Unknown', '1': 'Recovered/Resolved', '2': 'Recovering/Resolving',
        '3': 'Not Recovered/Not Resolved/Ongoing',
        '4': 'Recovered/Resolved with Sequelae', '5': 'Fatal',
    },
    'f_r_3_1_test_result_code': {
        '1': 'Positive', '2': 'Negative', '3': 'Borderline', '4': 'Inconclusive',
    },
    'g_k_1_characterisation_drug_role': {
        '1': 'Suspect', '2': 'Concomitant', '3': 'Interacting', '4': 'Drug Not Administered',
    },
    'g_k_8_action_taken_drug': {
        '0': 'Unknown', '1': 'Drug Withdrawn', '2': 'Dose Reduced',
        '3': 'Dose Increased', '4': 'Dose Not Changed', '9': 'Not Applicable',
    },
    'g_k_9_i_4_reaction_recur_readministration': {
        '1': 'Yes – Yes', '2': 'Yes – No', '3': 'Yes – Unknown', '4': 'No – Not Applicable',
    },
    'g_k_10_r_additional_information_drug': {
        '1': 'Counterfeit', '2': 'Overdose', '3': 'Drug Taken by the Father',
        '4': 'Drug Taken Beyond Expiry Date',
        '5': 'Batch/Lot Within Specifications', '6': 'Batch/Lot Not Within Specifications',
        '7': 'Medication Error', '8': 'Misuse', '9': 'Abuse',
        '10': 'Occupational Exposure', '11': 'Off-Label Use',
    },
}

NULL_FLAVOR_LABELS: Dict[str, str] = {
    'NI': 'No Information', 'MSK': 'Masked', 'UNK': 'Unknown',
    'NA': 'Not Applicable', 'ASKU': 'Asked But Unknown', 'NASK': 'Not Asked',
    'NINF': 'Negative Infinity', 'PINF': 'Positive Infinity',
}

AGE_UNIT_LABELS: Dict[str, str] = {
    '10.a': 'decade(s)', 'a': 'year(s)', 'mo': 'month(s)',
    'wk': 'week(s)', 'd': 'day(s)', 'h': 'hour(s)', 'min': 'minute(s)', 's': 'second(s)',
}

_LIST_TAGS: Set[str] = {
    'c_1_6_1_r_documents_held_sender', 'c_1_9_1_r_source_case_id',
    'c_1_10_r_identification_number_report_linked', 'c_2_r_primary_source_information',
    'c_4_r_literature_reference', 'c_5_1_r_study_registration',
    'd_7_1_r_structured_information_medical_history', 'd_8_r_past_drug_history',
    'd_9_2_r_cause_death', 'd_9_4_r_autopsy_determined_cause_death',
    'd_10_7_1_r_structured_information_parent_meddra_code', 'd_10_8_r_past_drug_history_parent',
    'e_i_reaction_event', 'f_r_results_tests_procedures_investigation_patient',
    'g_k_drug_information', 'g_k_2_3_r_substance_id_strength',
    'g_k_4_r_dosage_information', 'g_k_7_r_indication_use_case',
    'g_k_9_i_drug_reaction_matrix', 'g_k_9_i_2_r_assessment_relatedness_drug_reaction',
    'g_k_10_r_additional_information_drug', 'h_3_r_sender_diagnosis_meddra_code',
    'h_5_r_case_summary_reporter_comments_native_language',
}
