from typing import Any, Dict, List

from _constants import NULL_FLAVOR_LABELS, __version__

_SQL_DDL = """-- ============================================================
-- E2B R3 ICSR Database Schema  (SQLite / PostgreSQL compatible)
-- Generated by E2B R3 Import/Export Module v{version}
-- Standard: ICH E2B(R3)  |  License: GPL v3
-- ============================================================

CREATE TABLE IF NOT EXISTS icsr (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    imported_at TEXT    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS c1_identification (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                         INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    sender_safety_report_unique_id  TEXT,
    date_creation                   TEXT,
    type_report                     TEXT,
    date_first_received             TEXT,
    date_most_recent                TEXT,
    additional_documents_available  TEXT,
    fulfil_local_criteria           TEXT,
    worldwide_unique_case_id        TEXT,
    first_sender                    TEXT,
    other_case_ids_previous         TEXT,
    report_nullification_amendment  TEXT,
    reason_nullification_amendment  TEXT
);

CREATE TABLE IF NOT EXISTS c1_documents (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    c1_id           INTEGER REFERENCES c1_identification(id) ON DELETE CASCADE,
    document_name   TEXT
);

CREATE TABLE IF NOT EXISTS c1_source_case_ids (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    c1_id       INTEGER REFERENCES c1_identification(id) ON DELETE CASCADE,
    source      TEXT,
    case_id     TEXT
);

CREATE TABLE IF NOT EXISTS c1_linked_reports (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    c1_id           INTEGER REFERENCES c1_identification(id) ON DELETE CASCADE,
    report_number   TEXT
);

CREATE TABLE IF NOT EXISTS c2_primary_sources (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                     INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    reporter_title              TEXT,
    reporter_given_name         TEXT,
    reporter_middle_name        TEXT,
    reporter_family_name        TEXT,
    reporter_organisation       TEXT,
    reporter_department         TEXT,
    reporter_street             TEXT,
    reporter_city               TEXT,
    reporter_state              TEXT,
    reporter_postcode           TEXT,
    reporter_telephone          TEXT,
    reporter_country_code       TEXT,
    qualification               TEXT,
    primary_source_regulatory   TEXT
);

CREATE TABLE IF NOT EXISTS c3_sender (
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                 INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    sender_type             TEXT,
    sender_organisation     TEXT,
    sender_department       TEXT,
    sender_title            TEXT,
    sender_given_name       TEXT,
    sender_middle_name      TEXT,
    sender_family_name      TEXT,
    sender_street           TEXT,
    sender_city             TEXT,
    sender_state            TEXT,
    sender_postcode         TEXT,
    sender_country_code     TEXT,
    sender_telephone        TEXT,
    sender_fax              TEXT,
    sender_email            TEXT
);

CREATE TABLE IF NOT EXISTS c4_literature (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    literature_reference TEXT
);

CREATE TABLE IF NOT EXISTS c5_study (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    study_name          TEXT,
    sponsor_study_number TEXT,
    study_type          TEXT
);

CREATE TABLE IF NOT EXISTS c5_study_registrations (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    c5_id                       INTEGER REFERENCES c5_study(id) ON DELETE CASCADE,
    registration_number         TEXT,
    registration_country        TEXT
);

CREATE TABLE IF NOT EXISTS d_patient (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                         INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    patient_initials                TEXT,
    medical_record_gp               TEXT,
    medical_record_specialist       TEXT,
    medical_record_hospital         TEXT,
    medical_record_investigation    TEXT,
    date_birth                      TEXT,
    age_onset_num                   TEXT,
    age_onset_unit                  TEXT,
    gestation_period_num            TEXT,
    gestation_period_unit           TEXT,
    age_group                       TEXT,
    body_weight_kg                  TEXT,
    height_cm                       TEXT,
    sex                             TEXT,
    last_menstrual_period           TEXT,
    text_medical_history            TEXT,
    concomitant_therapies           TEXT,
    date_death                      TEXT,
    autopsy_done                    TEXT,
    parent_identification           TEXT,
    parent_date_birth               TEXT,
    parent_age_num                  TEXT,
    parent_age_unit                 TEXT,
    parent_last_menstrual_period    TEXT,
    parent_body_weight_kg           TEXT,
    parent_height_cm                TEXT,
    parent_sex                      TEXT,
    parent_text_medical_history     TEXT
);

CREATE TABLE IF NOT EXISTS d_medical_history (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id                  INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    meddra_version              TEXT,
    meddra_code                 TEXT,
    start_date                  TEXT,
    continuing                  TEXT,
    end_date                    TEXT,
    comments                    TEXT,
    family_history              TEXT
);

CREATE TABLE IF NOT EXISTS d_past_drugs (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id                  INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    drug_name                   TEXT,
    mpid_version                TEXT,
    mpid                        TEXT,
    phpid_version               TEXT,
    phpid                       TEXT,
    start_date                  TEXT,
    end_date                    TEXT,
    indication_meddra_version   TEXT,
    indication_meddra_code      TEXT,
    reaction_meddra_version     TEXT,
    reaction_meddra_code        TEXT
);

CREATE TABLE IF NOT EXISTS d_cause_death (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id      INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    meddra_version  TEXT,
    meddra_code     TEXT,
    cause_text      TEXT
);

CREATE TABLE IF NOT EXISTS d_autopsy_cause (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id      INTEGER REFERENCES d_patient(id) ON DELETE CASCADE,
    meddra_version  TEXT,
    meddra_code     TEXT,
    cause_text      TEXT
);

CREATE TABLE IF NOT EXISTS e_reactions (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                         INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    reaction_native_language        TEXT,
    reaction_language               TEXT,
    reaction_translation            TEXT,
    meddra_version                  TEXT,
    meddra_code                     TEXT,
    term_highlighted                TEXT,
    seriousness_death               TEXT,
    seriousness_life_threatening    TEXT,
    seriousness_hospitalisation     TEXT,
    seriousness_disabling           TEXT,
    seriousness_congenital          TEXT,
    seriousness_other               TEXT,
    date_start                      TEXT,
    date_end                        TEXT,
    duration_num                    TEXT,
    duration_unit                   TEXT,
    outcome                         TEXT,
    medical_confirmation            TEXT,
    country                         TEXT
);

CREATE TABLE IF NOT EXISTS f_tests (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    test_date           TEXT,
    test_name           TEXT,
    meddra_version      TEXT,
    meddra_code         TEXT,
    result_code         TEXT,
    result_value        TEXT,
    result_unit         TEXT,
    result_unstructured TEXT,
    normal_low          TEXT,
    normal_high         TEXT,
    comments            TEXT,
    more_info_available TEXT
);

CREATE TABLE IF NOT EXISTS g_drugs (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id                     INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    drug_role                   TEXT,
    mpid_version                TEXT,
    mpid                        TEXT,
    phpid_version               TEXT,
    phpid                       TEXT,
    product_name                TEXT,
    country_obtained            TEXT,
    investigational_blinded     TEXT,
    authorisation_number        TEXT,
    authorisation_country       TEXT,
    holder_name                 TEXT,
    cumulative_dose_num         TEXT,
    cumulative_dose_unit        TEXT,
    gestation_period_num        TEXT,
    gestation_period_unit       TEXT,
    action_taken                TEXT,
    additional_info_text        TEXT
);

CREATE TABLE IF NOT EXISTS g_substances (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id         INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    substance_name  TEXT,
    termid_version  TEXT,
    termid          TEXT,
    strength_num    TEXT,
    strength_unit   TEXT
);

CREATE TABLE IF NOT EXISTS g_dosages (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id                     INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    dose_num                    TEXT,
    dose_unit                   TEXT,
    number_units_interval       TEXT,
    interval_unit               TEXT,
    date_start                  TEXT,
    date_last_admin             TEXT,
    duration_num                TEXT,
    duration_unit               TEXT,
    batch_lot_number            TEXT,
    dosage_text                 TEXT,
    dose_form                   TEXT,
    route_administration        TEXT,
    parent_route_administration TEXT
);

CREATE TABLE IF NOT EXISTS g_indications (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id             INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    indication_text     TEXT,
    meddra_version      TEXT,
    meddra_code         TEXT
);

CREATE TABLE IF NOT EXISTS g_reaction_matrix (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id                     INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    reaction_index              TEXT,
    interval_admin_reaction_num TEXT,
    interval_admin_reaction_unit TEXT,
    interval_last_dose_num      TEXT,
    interval_last_dose_unit     TEXT,
    recur_readministration      TEXT
);

CREATE TABLE IF NOT EXISTS g_assessments (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    matrix_id       INTEGER REFERENCES g_reaction_matrix(id) ON DELETE CASCADE,
    source          TEXT,
    method          TEXT,
    result          TEXT
);

CREATE TABLE IF NOT EXISTS g_additional_info (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_id     INTEGER REFERENCES g_drugs(id) ON DELETE CASCADE,
    info_code   TEXT
);

CREATE TABLE IF NOT EXISTS h_narrative (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    icsr_id             INTEGER REFERENCES icsr(id) ON DELETE CASCADE,
    case_narrative      TEXT,
    reporter_comments   TEXT,
    sender_comments     TEXT
);

CREATE TABLE IF NOT EXISTS h_sender_diagnosis (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    narrative_id    INTEGER REFERENCES h_narrative(id) ON DELETE CASCADE,
    meddra_version  TEXT,
    meddra_code     TEXT
);

CREATE TABLE IF NOT EXISTS h_reporter_comments_native (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    narrative_id    INTEGER REFERENCES h_narrative(id) ON DELETE CASCADE,
    comments_text   TEXT,
    language        TEXT
);
"""


def _sq(v: Any) -> str:
    """Escape a value for SQL single-quoted string."""
    if v is None:
        return 'NULL'
    s = str(v).replace("'", "''")
    return f"'{s}'"


def _sv(raw: Any, field: str = '') -> str:
    """Get SQL-safe string for a raw parsed value."""
    if raw is None:
        return 'NULL'
    if isinstance(raw, dict):
        nf = raw.get('_null_flavor')
        if nf:
            return _sq(f'[{NULL_FLAVOR_LABELS.get(nf, nf)}]')
        v = raw.get('_value')
        return _sq(v) if v is not None else 'NULL'
    return _sq(str(raw))


def _insert(table: str, col_val: Dict[str, Any]) -> str:
    cols = ', '.join(col_val.keys())
    vals = ', '.join(str(v) for v in col_val.values())
    return f'INSERT INTO {table} ({cols}) VALUES ({vals});'


def _to_sql(data: Dict[str, Any], root_tag: str, dialect: str = 'sqlite',
            include_ddl: bool = True) -> str:
    lines: List[str] = []

    if include_ddl:
        ddl = _SQL_DDL.format(version=__version__)
        if dialect == 'postgresql':
            ddl = ddl.replace('INTEGER PRIMARY KEY AUTOINCREMENT',
                              'SERIAL PRIMARY KEY')
        lines.append(ddl)

    lines.append(f'\n-- Data exported from {root_tag}\n')
    lines.append(_insert('icsr', {}))
    lines.append('-- (icsr row uses auto-generated id=1 below)\n')

    icsr_id = 1

    # C.1
    c1 = data.get('c_1_identification_case_safety_report') or {}
    if c1:
        c1_row = {
            'icsr_id':                         icsr_id,
            'sender_safety_report_unique_id':  _sv(c1.get('c_1_1_sender_safety_report_unique_id')),
            'date_creation':                   _sv(c1.get('c_1_2_date_creation')),
            'type_report':                     _sv(c1.get('c_1_3_type_report')),
            'date_first_received':             _sv(c1.get('c_1_4_date_report_first_received_source')),
            'date_most_recent':                _sv(c1.get('c_1_5_date_most_recent_information')),
            'additional_documents_available':  _sv(c1.get('c_1_6_1_additional_documents_available')),
            'fulfil_local_criteria':           _sv(c1.get('c_1_7_fulfil_local_criteria_expedited_report')),
            'worldwide_unique_case_id':        _sv(c1.get('c_1_8_1_worldwide_unique_case_identification_number')),
            'first_sender':                    _sv(c1.get('c_1_8_2_first_sender')),
            'other_case_ids_previous':         _sv(c1.get('c_1_9_1_other_case_ids_previous_transmissions')),
            'report_nullification_amendment':  _sv(c1.get('c_1_11_1_report_nullification_amendment')),
            'reason_nullification_amendment':  _sv(c1.get('c_1_11_2_reason_nullification_amendment')),
        }
        lines.append(_insert('c1_identification', c1_row))
        c1_id = 1

        for doc in (c1.get('c_1_6_1_r_documents_held_sender') or []):
            lines.append(_insert('c1_documents', {
                'c1_id': c1_id,
                'document_name': _sv(doc.get('c_1_6_1_r_1_documents_held_sender') if isinstance(doc, dict) else doc),
            }))

        for src in (c1.get('c_1_9_1_r_source_case_id') or []):
            if isinstance(src, dict):
                lines.append(_insert('c1_source_case_ids', {
                    'c1_id':   c1_id,
                    'source':  _sv(src.get('c_1_9_1_r_1_source_case_id')),
                    'case_id': _sv(src.get('c_1_9_1_r_2_case_id')),
                }))

        for lnk in (c1.get('c_1_10_r_identification_number_report_linked') or []):
            lines.append(_insert('c1_linked_reports', {
                'c1_id':         c1_id,
                'report_number': _sv(lnk.get('c_1_10_r_identification_number_report_linked')
                                     if isinstance(lnk, dict) else lnk),
            }))

    # C.2
    for src in (data.get('c_2_r_primary_source_information') or []):
        if not isinstance(src, dict):
            continue
        lines.append(_insert('c2_primary_sources', {
            'icsr_id':                    icsr_id,
            'reporter_title':             _sv(src.get('c_2_r_1_1_reporter_title')),
            'reporter_given_name':        _sv(src.get('c_2_r_1_2_reporter_given_name')),
            'reporter_middle_name':       _sv(src.get('c_2_r_1_3_reporter_middle_name')),
            'reporter_family_name':       _sv(src.get('c_2_r_1_4_reporter_family_name')),
            'reporter_organisation':      _sv(src.get('c_2_r_2_1_reporter_organisation')),
            'reporter_department':        _sv(src.get('c_2_r_2_2_reporter_department')),
            'reporter_street':            _sv(src.get('c_2_r_2_3_reporter_street')),
            'reporter_city':              _sv(src.get('c_2_r_2_4_reporter_city')),
            'reporter_state':             _sv(src.get('c_2_r_2_5_reporter_state_province')),
            'reporter_postcode':          _sv(src.get('c_2_r_2_6_reporter_postcode')),
            'reporter_telephone':         _sv(src.get('c_2_r_2_7_reporter_telephone')),
            'reporter_country_code':      _sv(src.get('c_2_r_3_reporter_country_code')),
            'qualification':              _sv(src.get('c_2_r_4_qualification')),
            'primary_source_regulatory':  _sv(src.get('c_2_r_5_primary_source_regulatory_purposes')),
        }))

    # C.3
    c3 = data.get('c_3_information_sender_case_safety_report') or {}
    if c3:
        lines.append(_insert('c3_sender', {
            'icsr_id':             icsr_id,
            'sender_type':         _sv(c3.get('c_3_1_sender_type')),
            'sender_organisation': _sv(c3.get('c_3_2_sender_organisation')),
            'sender_department':   _sv(c3.get('c_3_3_1_sender_department')),
            'sender_title':        _sv(c3.get('c_3_3_2_sender_title')),
            'sender_given_name':   _sv(c3.get('c_3_3_3_sender_given_name')),
            'sender_middle_name':  _sv(c3.get('c_3_3_4_sender_middle_name')),
            'sender_family_name':  _sv(c3.get('c_3_3_5_sender_family_name')),
            'sender_street':       _sv(c3.get('c_3_4_1_sender_street_address')),
            'sender_city':         _sv(c3.get('c_3_4_2_sender_city')),
            'sender_state':        _sv(c3.get('c_3_4_3_sender_state_province')),
            'sender_postcode':     _sv(c3.get('c_3_4_4_sender_postcode')),
            'sender_country_code': _sv(c3.get('c_3_4_5_sender_country_code')),
            'sender_telephone':    _sv(c3.get('c_3_4_6_sender_telephone')),
            'sender_fax':          _sv(c3.get('c_3_4_7_sender_fax')),
            'sender_email':        _sv(c3.get('c_3_4_8_sender_email')),
        }))

    # C.4
    for lit in (data.get('c_4_r_literature_reference') or []):
        if isinstance(lit, dict):
            ref = _sv(lit.get('c_4_r_1_literature_reference'))
        else:
            ref = _sq(str(lit))
        lines.append(_insert('c4_literature', {'icsr_id': icsr_id, 'literature_reference': ref}))

    # C.5
    c5 = data.get('c_5_study_identification') or {}
    if c5:
        lines.append(_insert('c5_study', {
            'icsr_id':              icsr_id,
            'study_name':           _sv(c5.get('c_5_2_study_name')),
            'sponsor_study_number': _sv(c5.get('c_5_3_sponsor_study_number')),
            'study_type':           _sv(c5.get('c_5_4_study_type_reaction')),
        }))
        for reg in (c5.get('c_5_1_r_study_registration') or []):
            if isinstance(reg, dict):
                lines.append(_insert('c5_study_registrations', {
                    'c5_id':                1,
                    'registration_number':  _sv(reg.get('c_5_1_r_1_study_registration_number')),
                    'registration_country': _sv(reg.get('c_5_1_r_2_study_registration_country')),
                }))

    # D
    d = data.get('d_patient_characteristics') or {}
    if d:
        lines.append(_insert('d_patient', {
            'icsr_id':                      icsr_id,
            'patient_initials':             _sv(d.get('d_1_patient')),
            'medical_record_gp':            _sv(d.get('d_1_1_1_medical_record_number_source_gp')),
            'medical_record_specialist':    _sv(d.get('d_1_1_2_medical_record_number_source_specialist')),
            'medical_record_hospital':      _sv(d.get('d_1_1_3_medical_record_number_source_hospital')),
            'medical_record_investigation': _sv(d.get('d_1_1_4_medical_record_number_source_investigation')),
            'date_birth':                   _sv(d.get('d_2_1_date_birth')),
            'age_onset_num':                _sv(d.get('d_2_2a_age_onset_reaction_num')),
            'age_onset_unit':               _sv(d.get('d_2_2b_age_onset_reaction_unit')),
            'gestation_period_num':         _sv(d.get('d_2_2_1a_gestation_period_reaction_foetus_num')),
            'gestation_period_unit':        _sv(d.get('d_2_2_1b_gestation_period_reaction_foetus_unit')),
            'age_group':                    _sv(d.get('d_2_3_patient_age_group')),
            'body_weight_kg':               _sv(d.get('d_3_body_weight')),
            'height_cm':                    _sv(d.get('d_4_height')),
            'sex':                          _sv(d.get('d_5_sex')),
            'last_menstrual_period':        _sv(d.get('d_6_last_menstrual_period_date')),
            'text_medical_history':         _sv(d.get('d_7_2_text_medical_history')),
            'concomitant_therapies':        _sv(d.get('d_7_3_concomitant_therapies')),
            'date_death':                   _sv(d.get('d_9_1_date_death')),
            'autopsy_done':                 _sv(d.get('d_9_3_autopsy')),
            'parent_identification':        _sv(d.get('d_10_1_parent_identification')),
            'parent_date_birth':            _sv(d.get('d_10_2_1_date_birth_parent')),
            'parent_age_num':               _sv(d.get('d_10_2_2a_age_parent_num')),
            'parent_age_unit':              _sv(d.get('d_10_2_2b_age_parent_unit')),
            'parent_last_menstrual_period': _sv(d.get('d_10_3_last_menstrual_period_date_parent')),
            'parent_body_weight_kg':        _sv(d.get('d_10_4_body_weight_parent')),
            'parent_height_cm':             _sv(d.get('d_10_5_height_parent')),
            'parent_sex':                   _sv(d.get('d_10_6_sex_parent')),
            'parent_text_medical_history':  _sv(d.get('d_10_7_2_text_medical_history_parent')),
        }))
        pat_id = 1

        for mh in (d.get('d_7_1_r_structured_information_medical_history') or []):
            if isinstance(mh, dict):
                lines.append(_insert('d_medical_history', {
                    'patient_id':    pat_id,
                    'meddra_version': _sv(mh.get('d_7_1_r_1a_meddra_version_medical_history')),
                    'meddra_code':    _sv(mh.get('d_7_1_r_1b_medical_history_meddra_code')),
                    'start_date':     _sv(mh.get('d_7_1_r_2_start_date')),
                    'continuing':     _sv(mh.get('d_7_1_r_3_continuing')),
                    'end_date':       _sv(mh.get('d_7_1_r_4_end_date')),
                    'comments':       _sv(mh.get('d_7_1_r_5_comments')),
                    'family_history': _sv(mh.get('d_7_1_r_6_family_history')),
                }))

        for pd in (d.get('d_8_r_past_drug_history') or []):
            if isinstance(pd, dict):
                lines.append(_insert('d_past_drugs', {
                    'patient_id':               pat_id,
                    'drug_name':                _sv(pd.get('d_8_r_1_name_drug')),
                    'mpid_version':             _sv(pd.get('d_8_r_2a_mpid_version')),
                    'mpid':                     _sv(pd.get('d_8_r_2b_mpid')),
                    'phpid_version':            _sv(pd.get('d_8_r_3a_phpid_version')),
                    'phpid':                    _sv(pd.get('d_8_r_3b_phpid')),
                    'start_date':               _sv(pd.get('d_8_r_4_start_date')),
                    'end_date':                 _sv(pd.get('d_8_r_5_end_date')),
                    'indication_meddra_version':_sv(pd.get('d_8_r_6a_meddra_version_indication')),
                    'indication_meddra_code':   _sv(pd.get('d_8_r_6b_indication_meddra_code')),
                    'reaction_meddra_version':  _sv(pd.get('d_8_r_7a_meddra_version_reaction')),
                    'reaction_meddra_code':     _sv(pd.get('d_8_r_7b_reaction_meddra_code')),
                }))

        for cd in (d.get('d_9_2_r_cause_death') or []):
            if isinstance(cd, dict):
                lines.append(_insert('d_cause_death', {
                    'patient_id':    pat_id,
                    'meddra_version': _sv(cd.get('d_9_2_r_1a_meddra_version_cause_death')),
                    'meddra_code':    _sv(cd.get('d_9_2_r_1b_cause_death_meddra_code')),
                    'cause_text':     _sv(cd.get('d_9_2_r_2_cause_death')),
                }))

        for ac in (d.get('d_9_4_r_autopsy_determined_cause_death') or []):
            if isinstance(ac, dict):
                lines.append(_insert('d_autopsy_cause', {
                    'patient_id':    pat_id,
                    'meddra_version': _sv(ac.get('d_9_4_r_1a_meddra_version_autopsy_determined_cause_death')),
                    'meddra_code':    _sv(ac.get('d_9_4_r_1b_autopsy_determined_cause_death_meddra_code')),
                    'cause_text':     _sv(ac.get('d_9_4_r_2_autopsy_determined_cause_death')),
                }))

    # E
    for rx in (data.get('e_i_reaction_event') or []):
        if not isinstance(rx, dict):
            continue
        lines.append(_insert('e_reactions', {
            'icsr_id':                        icsr_id,
            'reaction_native_language':       _sv(rx.get('e_i_1_1a_reaction_primary_source_native_language')),
            'reaction_language':              _sv(rx.get('e_i_1_1b_reaction_primary_source_language')),
            'reaction_translation':           _sv(rx.get('e_i_1_2_reaction_primary_source_translation')),
            'meddra_version':                 _sv(rx.get('e_i_2_1a_meddra_version_reaction')),
            'meddra_code':                    _sv(rx.get('e_i_2_1b_reaction_meddra_code')),
            'term_highlighted':               _sv(rx.get('e_i_3_1_term_highlighted_reporter')),
            'seriousness_death':              _sv(rx.get('e_i_3_2a_results_death')),
            'seriousness_life_threatening':   _sv(rx.get('e_i_3_2b_life_threatening')),
            'seriousness_hospitalisation':    _sv(rx.get('e_i_3_2c_caused_prolonged_hospitalisation')),
            'seriousness_disabling':          _sv(rx.get('e_i_3_2d_disabling_incapacitating')),
            'seriousness_congenital':         _sv(rx.get('e_i_3_2e_congenital_anomaly_birth_defect')),
            'seriousness_other':              _sv(rx.get('e_i_3_2f_other_medically_important_condition')),
            'date_start':                     _sv(rx.get('e_i_4_date_start_reaction')),
            'date_end':                       _sv(rx.get('e_i_5_date_end_reaction')),
            'duration_num':                   _sv(rx.get('e_i_6a_duration_reaction_num')),
            'duration_unit':                  _sv(rx.get('e_i_6b_duration_reaction_unit')),
            'outcome':                        _sv(rx.get('e_i_7_outcome_reaction_last_observation')),
            'medical_confirmation':           _sv(rx.get('e_i_8_medical_confirmation_healthcare_professional')),
            'country':                        _sv(rx.get('e_i_9_identification_country_reaction')),
        }))

    # F
    for tst in (data.get('f_r_results_tests_procedures_investigation_patient') or []):
        if not isinstance(tst, dict):
            continue
        lines.append(_insert('f_tests', {
            'icsr_id':            icsr_id,
            'test_date':          _sv(tst.get('f_r_1_test_date')),
            'test_name':          _sv(tst.get('f_r_2_1_test_name')),
            'meddra_version':     _sv(tst.get('f_r_2_2a_meddra_version_test_name')),
            'meddra_code':        _sv(tst.get('f_r_2_2b_test_name_meddra_code')),
            'result_code':        _sv(tst.get('f_r_3_1_test_result_code')),
            'result_value':       _sv(tst.get('f_r_3_2_test_result_val_qual')),
            'result_unit':        _sv(tst.get('f_r_3_3_test_result_unit')),
            'result_unstructured':_sv(tst.get('f_r_3_4_result_unstructured_data')),
            'normal_low':         _sv(tst.get('f_r_4_normal_low_value')),
            'normal_high':        _sv(tst.get('f_r_5_normal_high_value')),
            'comments':           _sv(tst.get('f_r_6_comments')),
            'more_info_available':_sv(tst.get('f_r_7_more_information_available')),
        }))

    # G
    for drug_idx, drg in enumerate((data.get('g_k_drug_information') or []), 1):
        if not isinstance(drg, dict):
            continue
        lines.append(_insert('g_drugs', {
            'icsr_id':                  icsr_id,
            'drug_role':                _sv(drg.get('g_k_1_characterisation_drug_role')),
            'mpid_version':             _sv(drg.get('g_k_2_1_1a_mpid_version')),
            'mpid':                     _sv(drg.get('g_k_2_1_1b_mpid')),
            'phpid_version':            _sv(drg.get('g_k_2_1_2a_phpid_version')),
            'phpid':                    _sv(drg.get('g_k_2_1_2b_phpid')),
            'product_name':             _sv(drg.get('g_k_2_2_medicinal_product_name_primary_source')),
            'country_obtained':         _sv(drg.get('g_k_2_4_identification_country_drug_obtained')),
            'investigational_blinded':  _sv(drg.get('g_k_2_5_investigational_product_blinded')),
            'authorisation_number':     _sv(drg.get('g_k_3_1_authorisation_application_number')),
            'authorisation_country':    _sv(drg.get('g_k_3_2_country_authorisation_application')),
            'holder_name':              _sv(drg.get('g_k_3_3_name_holder_applicant')),
            'cumulative_dose_num':      _sv(drg.get('g_k_5a_cumulative_dose_first_reaction_num')),
            'cumulative_dose_unit':     _sv(drg.get('g_k_5b_cumulative_dose_first_reaction_unit')),
            'gestation_period_num':     _sv(drg.get('g_k_6a_gestation_period_exposure_num')),
            'gestation_period_unit':    _sv(drg.get('g_k_6b_gestation_period_exposure_unit')),
            'action_taken':             _sv(drg.get('g_k_8_action_taken_drug')),
            'additional_info_text':     _sv(drg.get('g_k_11_additional_information_drug')),
        }))
        drug_sql_id = drug_idx

        for sub in (drg.get('g_k_2_3_r_substance_id_strength') or []):
            if isinstance(sub, dict):
                lines.append(_insert('g_substances', {
                    'drug_id':        drug_sql_id,
                    'substance_name': _sv(sub.get('g_k_2_3_r_1_substance_name')),
                    'termid_version': _sv(sub.get('g_k_2_3_r_2a_substance_termid_version')),
                    'termid':         _sv(sub.get('g_k_2_3_r_2b_substance_termid')),
                    'strength_num':   _sv(sub.get('g_k_2_3_r_3a_strength_num')),
                    'strength_unit':  _sv(sub.get('g_k_2_3_r_3b_strength_unit')),
                }))

        for dos in (drg.get('g_k_4_r_dosage_information') or []):
            if isinstance(dos, dict):
                lines.append(_insert('g_dosages', {
                    'drug_id':                   drug_sql_id,
                    'dose_num':                  _sv(dos.get('g_k_4_r_1a_dose_num')),
                    'dose_unit':                 _sv(dos.get('g_k_4_r_1b_dose_unit')),
                    'number_units_interval':     _sv(dos.get('g_k_4_r_2_number_units_interval')),
                    'interval_unit':             _sv(dos.get('g_k_4_r_3_definition_interval_unit')),
                    'date_start':                _sv(dos.get('g_k_4_r_4_date_time_drug')),
                    'date_last_admin':           _sv(dos.get('g_k_4_r_5_date_time_last_administration')),
                    'duration_num':              _sv(dos.get('g_k_4_r_6a_duration_drug_administration_num')),
                    'duration_unit':             _sv(dos.get('g_k_4_r_6b_duration_drug_administration_unit')),
                    'batch_lot_number':          _sv(dos.get('g_k_4_r_7_batch_lot_number')),
                    'dosage_text':               _sv(dos.get('g_k_4_r_8_dosage_text')),
                    'dose_form':                 _sv(dos.get('g_k_4_r_9_1_pharmaceutical_dose_form')),
                    'route_administration':      _sv(dos.get('g_k_4_r_10_1_route_administration')),
                    'parent_route_administration': _sv(dos.get('g_k_4_r_11_1_parent_route_administration')),
                }))

        for ind in (drg.get('g_k_7_r_indication_use_case') or []):
            if isinstance(ind, dict):
                lines.append(_insert('g_indications', {
                    'drug_id':        drug_sql_id,
                    'indication_text': _sv(ind.get('g_k_7_r_1_indication_primary_source')),
                    'meddra_version':  _sv(ind.get('g_k_7_r_2a_meddra_version_indication')),
                    'meddra_code':     _sv(ind.get('g_k_7_r_2b_indication_meddra_code')),
                }))

        for matrix_idx, mx in enumerate((drg.get('g_k_9_i_drug_reaction_matrix') or []), 1):
            if isinstance(mx, dict):
                lines.append(_insert('g_reaction_matrix', {
                    'drug_id':                      drug_sql_id,
                    'reaction_index':               _sq(str(mx.get('g_k_9_i_1_reaction_assessed', ''))),
                    'interval_admin_reaction_num':  _sv(mx.get('g_k_9_i_3_1a_interval_drug_administration_reaction_num')),
                    'interval_admin_reaction_unit': _sv(mx.get('g_k_9_i_3_1b_interval_drug_administration_reaction_unit')),
                    'interval_last_dose_num':       _sv(mx.get('g_k_9_i_3_2a_interval_last_dose_drug_reaction_num')),
                    'interval_last_dose_unit':      _sv(mx.get('g_k_9_i_3_2b_interval_last_dose_drug_reaction_unit')),
                    'recur_readministration':       _sv(mx.get('g_k_9_i_4_reaction_recur_readministration')),
                }))
                matrix_sql_id = matrix_idx
                for asmnt in (mx.get('g_k_9_i_2_r_assessment_relatedness_drug_reaction') or []):
                    if isinstance(asmnt, dict):
                        lines.append(_insert('g_assessments', {
                            'matrix_id': matrix_sql_id,
                            'source':    _sv(asmnt.get('g_k_9_i_2_r_1_source_assessment')),
                            'method':    _sv(asmnt.get('g_k_9_i_2_r_2_method_assessment')),
                            'result':    _sv(asmnt.get('g_k_9_i_2_r_3_result_assessment')),
                        }))

        for ai in (drg.get('g_k_10_r_additional_information_drug') or []):
            val = ai.get('g_k_10_r_additional_information_drug') if isinstance(ai, dict) else ai
            lines.append(_insert('g_additional_info', {
                'drug_id':   drug_sql_id,
                'info_code': _sv(val),
            }))

    # H
    h = data.get('h_narrative_case_summary') or {}
    if h:
        lines.append(_insert('h_narrative', {
            'icsr_id':            icsr_id,
            'case_narrative':     _sv(h.get('h_1_case_narrative')),
            'reporter_comments':  _sv(h.get('h_2_reporter_comments')),
            'sender_comments':    _sv(h.get('h_4_sender_comments')),
        }))
        narr_id = 1

        for diag in (h.get('h_3_r_sender_diagnosis_meddra_code') or []):
            if isinstance(diag, dict):
                lines.append(_insert('h_sender_diagnosis', {
                    'narrative_id':  narr_id,
                    'meddra_version': _sv(diag.get('h_3_r_1a_meddra_version_sender_diagnosis')),
                    'meddra_code':    _sv(diag.get('h_3_r_1b_sender_diagnosis_meddra_code')),
                }))

        for cmt in (h.get('h_5_r_case_summary_reporter_comments_native_language') or []):
            if isinstance(cmt, dict):
                lines.append(_insert('h_reporter_comments_native', {
                    'narrative_id':  narr_id,
                    'comments_text': _sv(cmt.get('h_5_r_1a_case_summary_reporter_comments_text')),
                    'language':      _sv(cmt.get('h_5_r_1b_case_summary_reporter_comments_language')),
                }))

    return '\n'.join(lines)
